language: generic
matrix:
   include:
     - os: linux
       dist: xenial
       sudo: required
     - os: osx
       osx_image: xcode10.2
     # - os: osx
     #   osx_image: xcode11.0
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test -c debug --enable-code-coverage
    - swift test -c release
